### PR TITLE
Burtons/optimizations - adding declerations

### PR DESCRIPTION
**Pull request by burtonsamograd**
These declerations added to vecto float-octet, imult, lerp and prelerp, combined with some other changes to cl-vector (to be submitted) gave a 50% speedup during my tests with no changes to the image output.  Further declerations were tried to muffle SBCL optimization warnings but they were left out as they gave no performance improvements.

Profiling was done by rendering feedlike-icon 100 times and also on a personal image of mine where the rendering went from 20 seconds to ~10.

This is my first attempt at optimization with decleratoins so any advice on style is appreciated.

### CODE REVIEW

**Comment by xach** [comment]
Thanks for the contribution. I can't accept it as-is.

* I don't want (safety 0) declarations in library code
* FIXNUM is a bad type to use; it is much better to use explicit ranges like (integer 0 <whatever>) or ([un]signed-byte <size>)
* I don't like (the <type> <expression>) forms. I prefer modular arithmetic triggers like (logand <mask> <expression>).

**Comment by xach** [comment]
Regarding FIXNUM alternatives, if you don't know the range, there shouldn't be a declaration.

**Comment by burtonsamograd** [comment]
Are the single-float declerations ok?

**Comment by xach** [comment]
Not sure - is it accurate?

**Comment by burtonsamograd** [comment]
Is there an input range on imult, lerp and prelerp?

Re: single-float declerations, they looked accurate to me.  I just wanted to know if you wanted single or double float calculations.

**Comment by xach** [comment]
I think for most stuff the range for integer stuff is 0-255 and the range for floats is 0.0-1.0, but I don't know for sure on all of them.

**Pull request closed without merging**
