### PR TITLE
Add image composition, VECTO-IMAGO contrib, custom allocators and returning images

### PR DESCRIPTION
**Pull request by phoe**
# Custom allocators

The `with-canvas` option now accepts the `:image-data-allocator` keyword. It must be a function that will be called with one argument (the size of the resulting vector) and must return a vector of `(unsigned-byte 8)` which will be used as storage for the image data.

This is useful e.g. for using a [static vector](https://github.com/sionescu/static-vectors) for the storage in order to make the resulting PNG data interoperable with foreign libraries.

Example:

```lisp
(flet ((allocate (size)
         (static-vectors:make-static-vector size :initial-element 0)))
  (with-canvas (:width ... :height ...
                :image-data-allocator #'allocate)
    ...))
```

# Returning images

The function `(zpng-object)` can now be used to return the ZPNG object representing the canvas.

# Image composition / `VECTO-IMAGO`

This adds a protocol GF for simple image composition and a `vecto-imago` ASDF system, which contains an example (but working and optimized) implementation method for Imago's `rgb-image` class. This means that Vecto gains a way to overlay raster images onto its canvas.

The interface is very crude, as it explicitly disregards all transformations of Vecto coordinates, but I expect that all modifications of the raster layers (scaling, rotation, et al) are going to happen on the Imago side. This is in order to keep the Vecto codebase focused on raster graphics.

Example code:
```lisp
(v:with-canvas (:width 1000 :height 1000)
  ;; Background
  (progn (v:set-gradient-fill 0 0 1 0 0 1
                              1000 1000 0 1 0 0)
         (v:move-to 0 0)
         (v:line-to 1000 0)
         (v:line-to 1000 1000)
         (v:line-to 0 1000)
         (v:line-to 0 0)
         (v:fill-path))
  ;; Foreground
  (let* ((image (imago:read-png #p"ichi-t.png")))
    (v:compose image 50 50))
  (v:save-png #p"/tmp/vecto.png"))
```

`ichi-t.png`:
ichi-t

Result:
vecto

### CODE REVIEW

**Comment by phoe** [comment]
Review comments are welcome in case someone wants to propose e.g. a better interface for this.

**Comment by xach** [comment]
> explicitly disregards all transformations of Vecto coordinates

This is problematic for me - I typically use VECTOMETRY, which uses a
bounding rect as its canvas basis, and the lower-left of the rect need not
be at the origin. So I often don't actually know the true, non-transformed
origin.

So I *think* that means I want you to honor translate - converted to
integral coordinates by CEILING as with vectometry:with-box-canvas. But you
can ignore rotate or skew.

**Comment by phoe** [comment]
I've updated the PR with allocators and image returning and a minor fix to the documentation for composition. If that's too messy for your taste, I'll reorganize it.

How does `vecto` store translation data? I see that there's a slot for a transformation matrix in the current graphic state, but how do I interpret the six values that are there?

**Comment by phoe** [comment]
Fix done - now the below code produces the same effect. Note that I use `translate` instead of explicitly providing coordinates to `compose`.

```lisp
(v:with-canvas (:width 1000 :height 1000)
  ;; Background
  (progn (v:set-gradient-fill 0 0 1 0 0 1
                              1000 1000 0 1 0 0)
         (v:move-to 0 0)
         (v:line-to 1000 0)
         (v:line-to 1000 1000)
         (v:line-to 0 1000)
         (v:line-to 0 0)
         (v:fill-path))
  ;; Foreground
  (let* ((image (imago:read-png #p"~/Downloads/ichi-t.png")))
    (v:translate 50 50)
    (v:compose image))
  (v:save-png #p"/tmp/vecto.png")
  v::*graphics-state*)
```

**Comment by xach** [comment]
I'm sorry if I gave the impression that the coordinates should be removed
from COMPOSE - they should remain. But they should operate relative to the
current translation, rather than ignoring it.

**Comment by phoe** [comment]
D'oh!

Re-added - now the following code also works the same way.

```lisp
(v:with-canvas (:width 1000 :height 1000)
  ;; Background
  (progn (v:set-gradient-fill 0 0 1 0 0 1
                              1000 1000 0 1 0 0)
         (v:move-to 0 0)
         (v:line-to 1000 0)
         (v:line-to 1000 1000)
         (v:line-to 0 1000)
         (v:line-to 0 0)
         (v:fill-path))
  ;; Foreground
  (let* ((image (imago:read-png #p"~/Downloads/ichi-t.png")))
    (v:translate 25 25)
    (v:compose image 25 25))
  (v:save-png #p"/tmp/vecto.png"))
```

**Comment by phoe** [comment]
To clarify, these all work the same way now:

```lisp
    (v:translate 25 25)
    (v:compose image 25 25)
```

```lisp
    (v:compose image 50 50)
```

```lisp
    (v:translate 50 50)
    (v:compose image 0 0)
```

**Comment by phoe** [comment]
...maybe the arguments to `compose` can be `&optional x y` and they can default to 0, if you consider that last version to be a little unclean. Or we can keep the composition offsets mandatory and explicit.

**Comment by xach** [comment]
Mandatory and explicit is what I'd prefer.

**Comment by phoe** [comment]
OK, then I guess no more API changes are required.

**Comment by phoe** [comment]
Is there anything else that you'd like from me with regard to this PR?

**Comment by phoe** [comment]
Bip bop

**Pull request merged**
